[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd backend && npm ci', 'cd frontend && npm ci --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'